myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL,
     document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path
from . import views
from .views import ProductListView, ProductDetailView


app_name = 'shop'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('<slug:slug>/', ProductListView.as_view(), name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/shop/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
    unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
        models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])
class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    indexes = [
        models.Index(fields=['id', 'slug']),
        models.Index(fields=['name']),
        models.Index(fields=['-created']),
    ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'slug': self.slug, 'id': self.id})

myshop/cart/views.py
from django.shortcuts import render

# Create your views here.

myshop/shop/views.py
from lib2to3.fixes.fix_input import context

from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Product, Category

class ProductListView(ListView):
    context_object_name = 'products'
    template_name = 'shop/product/list.html'

    def get_queryset(self):
        # Основной фильтр для доступных продуктов
        queryset = Product.objects.filter(available=True)

        # Если передан slug, фильтруем по категории
        slug = self.kwargs.get('slug')
        if slug:
            category = get_object_or_404(Category, slug=slug)
            queryset = queryset.filter(category=category)
        return queryset

    def get_context_data(self, **kwargs):
        # Добавляем категории в контекст
        slug = self.kwargs.get('slug')
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        if slug:
            category = get_object_or_404(Category, slug=slug)
            context['category'] = category
        return context

class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product_detail'
    template_name = 'shop/product/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id = self.kwargs.get('id')
        slug = self.kwargs.get('slug')
        product = get_object_or_404(Product, id=id, slug=slug)
        context['product'] = product
        return context

#405

myshop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
     <head>
         <meta charset="utf-8" />
         <title>{% block title %}My shop{% endblock %}</title>
         <link href="{% static 'css/base.css' %}" rel="stylesheet">
     </head>
 <body>
     <div id="header">
         <a href="/" class="logo">My shop</a>
     </div>
         <div id="subheader">
             <div class="cart">
                Your cart is empty.
             </div>
         </div>
     <div id="content">
         {% block content %}
         {% endblock %}
     </div>
 </body>
</html>

myshop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
 {{ product.name }}
{% endblock %}
{% block content %}
 <div class="product-detail">
 <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
 <h1>{{ product.name }}</h1>
 <h2>
 <a href="{{ product.category.get_absolute_url }}">
 {{ product.category }}
 </a>
 </h2>
 <p class="price">${{ product.price }}</p>
 {{ product.description|linebreaks }}
 </div>
{% endblock %}

myshop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
   <h3>Categories</h3>
   <ul>
      <li {% if not category %}class="selected"{% endif %}>
      <a href="{% url 'shop:product_list' %}">All</a>
      </li>
      {% for c in categories %}
      <li {% if category.slug == c.slug %}class="selected"
      {% endif %}>
      <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
      </li>
      {% endfor %}
   </ul>
</div>
<div id="main" class="product-list">
   <h1>{% if category %}{{ category.name }}{% else %}Products
      {% endif %}
   </h1>
   {% for product in products %}
   <div class="item">
      <a href="{{ product.get_absolute_url }}">
      <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
      </a>
      <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
      <br>
      ${{ product.price }}
   </div>
   {% endfor %}
</div>
{% endblock %}